routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\FeesClearanceController;
use App\Http\Controllers\ExamResultController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth:sanctum']], function(){
    Route::get('/my-results', [ExamResultController::class, 'myresults'])->name('my-results');
    Route::get('/results/clearance/{user:slug}', [ExamResultController::class, 'show'])->name('my-clearance');
    //for accounts
    Route::get('/dashboard/fees-clearances', [FeesClearanceController::class, 'index'])->name('fees-clearances');
    Route::get('/dashboard', [FeesClearanceController::class, 'index'])->name('dashboard');
    Route::get('/dashboard/fees-clearances/{user:slug}', [FeesClearanceController::class, 'show'])->name('fees-clearance');
    Route::get('/users/registration', [UserController::class, 'create'])->name('user-registration');
    Route::post('/users/registration', [UserController::class, 'store']);
        
    Route::get('/practice', function(){
        return view('practice');
    });
    
});
    Route::get('/users/activate-account',[UserController::class, 'activate']);
    Route::put('/users/activate-account',[UserController::class, 'activation']);
// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

app/Models/Fee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Fee extends Model
{
    use HasFactory;
    protected $guarded = [];
    protected $casts =[
        'cleared_at'=>'datetime',
    ];

    public function intake()
    {
        return $this->belongsTo(Intake::class);
    }

    public function approver()
    {
        return $this->belongsTo(User::class, 'clearer_id');
    } 

    public function user()
    {
        return $this->belongsto(User::class);
    } 

    public function result()   
    {
        return hasMany(Result::class);
    }

     public function files()
     {
      return $this->morphMany(File::class, 'fileable');
     }    
}

app/Http/Livewire/Comment/CommentUpload.php
<?php

namespace App\Http\Livewire\Comment;

use Livewire\Component;
use Livewire\WithFileUploads;
use App\Models\File;
use Auth;

class CommentUpload extends Component
{
    use WithFileUploads;
    public $isFromStudent = false;
    public $possibleNewProofOfPayment = false;
    public $fileName;
    public $fileableType;
    public $fileableId;
    public $comment;
    public $url;
    /*public $title;*/
    public $reply_id;
    public $iteration=1;
    public $randomu =1;
    public $files;
    //public $files =[];

    protected function resetForm()
    {
        $this->reset('fileName');
    }
    public function clearErrors()
    {
        $this->resetValidation();
    }
    public function uploadFile()
    {
       
       $morphTo = $this->fileableType::findOrFail($this->fileableId);
        
        $validateData =$this->validate([
            'fileName'=>'nullable|mimes:jpg,gif,jpeg,png,pdf|max:2048',
            'comment'=>'required_without:fileName',
            ],
                [
                    'fileName.required_without:comment' => 'You can not send a blank message',
                ],
                [
                    'fileName.mimes:pdf,jpg,gif,jpeg,png' => 'The file must be 
                    in the format: pdf, jpg, gif, jpeg, png',
                ], 
                [
                    'fileName.max' => 'The selected file size must not exceed 2 MB',
                ],     
                [
                    'comment.required_without:fileName' => 'You can not submit an empty message',
                ], 
           

        );
        /**
         * store file
         */
        if(!empty($this->fileName)){            
            $url = $this->fileName->store('uploaded-files','public');
        }
        else{
            $url = '';
        }
            $morphTo->files()->create(['url' =>$url, 'body' =>$this->comment,'user_id' => Auth::user()->id]);
            $this->fileName = null;
            $this->comment = null;
            $this->iteration++;
            $this->fileName = null;
            $this->randomu++;
            /**
             * update Fee model if user was declined and is sending a new file
             */
            if($this->possibleNewProofOfPayment)
            {
                if(!is_null($morphTo->clearer_id))
                {
                   $morphTo->update(['clearer_id'=>NULL]); 
                }
                
            }
            $this->emit('updateComments');
            $this->resetValidation();

            session()->flash('message', 'Your message was successfully sent.');  
    }
/*    public function showFiles()
    {
        /**
         * find the model that is associated with the file (file)
         */
       /* $morphTo = $this->fileableType::findOrFail($this->fileableId);
        $files = $morphTo->files()->latest()->get();
        return $files;*/

   // }*/

    // public function deleteFile($id)
    // {
    //     $file =file::findOrFail($id);
    //     unlink('storage/'.$file->url);
    //     $file->delete();    
    //     session()->flash('message', 'The file was successfully deleted.');  
    // }
    public function mount($fileableId, $fileableType, $isFromStudent,$possibleNewProofOfPayment = false)
    {
        $this->fileableId = $fileableId;
        $this->fileableType = $fileableType;
        $this->isFromStudent = $isFromStudent;
        $this->possibleNewProofOfPayment = $possibleNewProofOfPayment;
    }
    public function render()
    {
      //  $this->files = $this->showFiles();
        return view('livewire.comment.comment-upload');
    }
}

app/Http/Livewire/Comment/GetComments.php
<?php

namespace App\Http\Livewire\Comment;

use Livewire\Component;

class GetComments extends Component
{
    protected $listeners = ['updateComments' => 'render'];
    public $fileableType;
    public $fileableId; 
    public $comments; 
    public $isFromStudent;  
    
    public function mount($fileableId, $fileableType, $isFromStudent)
    {
        $this->fileableId = $fileableId;
        $this->fileableType = $fileableType;
        $this->isFromStudent = $isFromStudent;
    } 
    public function showComments()
    {
        $morphTo = $this->fileableType::findOrFail($this->fileableId);
        $comments = $morphTo->files()->with('user','fee')->oldest()->get();
        return $comments;
    }    

    public function render()
    {
        $this->comments = $this->showComments();
        //dd($this->comments);
        return view('livewire.comment.get-comments');
    }
}

app/Http/Livewire/Fees/ClearStudent.php
<?php

namespace App\Http\Livewire\Fees;

use Livewire\Component;
use App\Http\Livewire\Modal;
use App\Models\Fee;
use App\Models\User;
use Auth;

class ClearStudent extends Modal
{
    public $fee;
    public $surname;
    public $first_name;
    public $discipline;
    public $status;
    public $created;
    public $noOfFiles;
    //public $defaultAccountsPersonnel;
    public function resetForm()
    {
        $this->resetErrorBag();
    }
    public function updateFeesClearanceState($slug)
    {
        $this->show();
        //$this->defaultAccountsPersonnel = User::where('email','accounts@hrepoly.ac.zw')->firstOrFail(); //default accounts dept account to be used in messages
        $this->fee =Fee::where('slug',$slug)->with('user','files','user.results')->firstOrFail(); 
        $this->noOfFiles = $this->fee->files()->count();
        $this->created = $this->fee->user->created_at->diffForHumans();
        $this->surname = $this->fee->user->second_name;
        $this->first_name =$this->fee->user->first_name;
        $this->discipline = $this->fee->user->results[0]->discipline;
        if($this->fee->cleared_at == null && $this->fee->is_cleared == false)
        {
            $this->status = 'Pending';
        }
        elseif(!$this->fee->cleared_at == null && $this->fee->is_cleared == false)
        {
            $this->status = 'Declined';
        }
        if(!$this->fee->cleared_at == null & $this->fee->is_cleared)
        {
            $this->status = 'Cleared';
        }       


    }  

    protected function authorisation()
    {

        /**
         * abort if student is already cleared
         */
                
        if($this->fee->is_cleared)

        {            
            session()->flash('warning',"The student: '$this->surname $this->first_name' is already cleared");
            $this->hide();
            return redirect('/dashboard'); 
            //change url to view more mode          

        }
        /**
         *  abort if the processing personnel is to approve own student payment
         */      
         

        if(Auth::user()->id ==$this->fee->user_id)
        {            
            session()->flash('warning',"Failed! You cannot process your own account ");
            $this->hide();
            return redirect('/dashboard/fees-clearances/');  
            //change url to view more mode 
                      
        }

    } 

    public function approveStudent()
    {
        //$this->authorisation();
        /**
         * abort if student is already cleared
         */
                
        if($this->fee->is_cleared)

        {            
            session()->flash('warning',"The student: '$this->surname $this->first_name' is already cleared");
            $this->hide();
            return redirect('/dashboard/fees-clearances/'.$this->fee->user->slug); 
            //change url to view more mode          

        }
        /**
         *  abort if the processing personnel is to approve own student payment
         */      
         

        if(Auth::user()->id ==$this->fee->user_id)
        {            
            session()->flash('warning',"Failed! You cannot process your own account ");
            $this->hide();
            return redirect('/dashboard/fees-clearances/'.$this->fee->user->slug);  
            //change url to view more mode 
                      
        }   
        
        $this->fee->update(['is_cleared'=>true, 'clearer_id'=>Auth::user()->id, 'cleared_at'=>now()]);  
         $this->fee->files()->create(['body' =>'Your account was successfully processed','user_id' => Auth::user()->id]);          
         session()->flash('message',"The student: '$this->surname $this->first_name's account was successfully updated");
        $this->hide(); 
         return redirect('/dashboard/fees-clearances/'.$this->fee->user->slug);        
    }


    public function declineStudent()
    {
        //$this->authorisation();
        /**
         * abort if student is already cleared
         */
                
        if($this->fee->is_cleared)

        {
            
            session()->flash('warning',"The student: '$this->surname $this->first_name' is already cleared");
            $this->hide();
            return redirect('/dashboard/fees-clearances/'.$this->fee->user->slug); 
            //change url to view more mode          

        }

        /**
         *  abort if the processing personnel is to approve own student payment
         */  
        if(Auth::user()->id ==$this->fee->user_id)
        {            
            session()->flash('warning',"Failed! You cannot process your own account ");
            $this->hide();
            return redirect('/dashboard/fees-clearances/'.$this->fee->user->slug);  
            //change url to view more mode 
                      
        }        

         $this->fee->update(['is_cleared'=>false, 'clearer_id'=>Auth::user()->id, 'cleared_at'=>now()]);  
         $this->fee->files()->create(['body' =>'Your account is in arrears, please clear the arrears and upload your proof of payment','user_id' => Auth::user()->id]);     
        session()->flash('message',"The student: '$this->surname $this->first_name's account was successfully updated");
        $this->hide();
        return redirect('/dashboard/fees-clearances/'.$this->fee->user->slug);        
    }    

    public function render()
    {  // $fee = $this->fee->with('user')->firstOrFail();   
        return view('livewire.fees.clear-student');
    }
}

app/Http/Livewire/Modal.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Modal extends Component
{

    public $show = false;

    protected $listeners = ['show','updateFeesClearanceState'];

    public function show()
    {
        $this->show = true;
        $this->resetForm();
        $this->resetValidation();
    }

    public function hide()
    {
        $this->show = false;
    }
}

resources/views/livewire/fees/clear-student.blade.php
<div>
    <x-modal wire:model="show">   
        <!-- content -->
      <x-slot name="title">
        Fees Clearance: 
      </x-slot>
      <div class="m-4 p-4">
         <div class="md:col-span-2 xl:col-span-1">
            <div class="rounded bg-indigo-500 p-3">
              <div class="flex justify-between py-1 text-white">
                <h3 class="text-sm font-semibold overflow-auto">  {{$surname}}  {{$first_name?? 'default'}}</h3>
                <p class="uppercase text-sm"> ID No. {{$fee->user->national_id?? 'default'}}</p>
              </div>
              <div class="text-sm text-black dark:text-gray-50 mt-2">
                <div class="bg-white  p-2 rounded mt-1 border-b border-indigo-100 text-lg font-semibold">  {{$discipline}}</div>
                <div class="bg-white  p-2 rounded mt-1 border-b border-indigo-100 ">
                  Registered online
                  <div class="text-gray-500  mt-2 ml-2 flex justify-between items-start">
                    <span class="text-xs flex items-center">
                      <svg class="h-4 fill-current mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50"><path d="M11 4c-3.855 0-7 3.145-7 7v28c0 3.855 3.145 7 7 7h28c3.855 0 7-3.145 7-7V11c0-3.855-3.145-7-7-7zm0 2h28c2.773 0 5 2.227 5 5v28c0 2.773-2.227 5-5 5H11c-2.773 0-5-2.227-5-5V11c0-2.773 2.227-5 5-5zm25.234 9.832l-13.32 15.723-8.133-7.586-1.363 1.465 9.664 9.015 14.684-17.324z"></path></svg>
                      &nbsp;{{$created}}
                    </span>
                            Status: 
                     @if($status =='Pending')
                        <span class="px-2 py-1 font-semibold leading-tight text-yellow-700 bg-yellow-100 rounded-full"> 
                           {{$status}}
                        </span>                         
                     @elseif($status =='Declined')
                        <span class="px-2 py-1 font-semibold leading-tight text-red-700 bg-red-100 rounded-full"> 
                            {{$status}}
                        </span>
                     @elseif($status =='Cleared')
                        <span class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full"> 
                            {{$status}}
                        </span>
                     @endif                            
                  </div>
                </div>
                <div class="bg-white p-2 rounded mt-1 border-b border-gray-100 ">Check fees payment with Pastel system or uploaded files</div>
                <div class="bg-white p-2 rounded mt-1 border-b border-gray-100">
                  Clear only if is a <span class="text-green-700">paid</span> up student, otherwise <span class="text-red-700">DECLINE</span>
                  <div class="text-gray-500 dark:text-gray-200 mt-2 ml-2 flex justify-between items-start">
                    <span class="text-xs flex items-center">
                      <svg class="h-4 fill-current mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50"><path d="M11 4c-3.855 0-7 3.145-7 7v28c0 3.855 3.145 7 7 7h28c3.855 0 7-3.145 7-7V11c0-3.855-3.145-7-7-7zm0 2h28c2.773 0 5 2.227 5 5v28c0 2.773-2.227 5-5 5H11c-2.773 0-5-2.227-5-5V11c0-2.773 2.227-5 5-5zm25.234 9.832l-13.32 15.723-8.133-7.586-1.363 1.465 9.664 9.015 14.684-17.324z"></path></svg>
                    @if($noOfFiles >0)
                      <p class="space-x-2">
                        <a href="/dashboard/fees-clearances/{{$fee->user->slug}}">
                          {{$noOfFiles}}
                          <span class="text-xl">&#128240</span> uploaded files
                        </a>
                        
                      </p>
                    @endif
                    </span>
                  </div>
                </div>
                <p class="mt-3 text-gray-600 dark:text-gray-400">& BE SURE...</p>
              </div>
            </div>
          </div> 

        <div class="flex justify-center pb-3 text-grey-dark my-4">
          <div class="text-center mr-3 border-r mx-8 pr-3">
            <h2></h2>
            <button class="font-semibold text-green-500" wire:click="approveStudent"  wire:loading.remove wire:target="approveStudent">Clear</button>
                  <span wire:loading wire:target="approveStudent">
                    Processing ...
                  </span>             
          </div>
          <div class="ml-16 text-center">
            <h2></h2>
            <button class="font-semibold text-red-700" wire:click="declineStudent"  wire:loading.remove wire:target="declineStudent">Decline</button>
                  <span wire:loading wire:target="declineStudent">
                    Processing ...
                  </span>            
          </div>
        </div>        
                                             

      </div>
  </x-modal>
</div>