routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\FeesClearanceController;
use App\Http\Controllers\ExamResultController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth:sanctum']], function(){
    Route::get('/my-results', [ExamResultController::class, 'myresults'])->name('my-results');
    Route::get('/results/clearance/{user:slug}', [ExamResultController::class, 'show'])->name('my-clearance');
    //for accounts
    Route::get('/dashboard/fees-clearances', [FeesClearanceController::class, 'index'])->name('fees-clearances');
    Route::get('/dashboard', [FeesClearanceController::class, 'index'])->name('dashboard');
    Route::get('/dashboard/fees-clearances/{user:slug}', [FeesClearanceController::class, 'show'])->name('fees-clearance');
    Route::get('/users/registration', [UserController::class, 'create'])->name('user-registration');
    Route::post('/users/registration', [UserController::class, 'store']);
        
    Route::get('/practice', function(){
        return view('practice');
    });
    
});
    Route::get('/users/activate-account',[UserController::class, 'activate']);
    Route::put('/users/activate-account',[UserController::class, 'activation']);
// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

app/Models/Result.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Result extends Model
{
    use HasFactory;
    protected $guarded =[];

    public function getCourseCodeAttribute($code)
    {
        $code =$code[0];
        if($code =='3' || $code == '4')
        {
            return 'National Certificate';
        }
        elseif($code =='5' || $code == '6')
        {
            return 'National Diploma';
        }
        elseif($code =='7' || $code == '8')
        {
            return 'Higher National Diploma';
        } 

    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/results/myresults.blade.php
<div>
  <style>
  @media print
  {
    .no-print{
      display: none;
    }
  }
/*.exam_results2{
    position:absolute;
    z-index:1;*/
/*  content: ' Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam quis suscipit non, quam explicabo perferendis maxime, blanditiis id amet odit neque. Minus alias deleniti neque recusandae voluptates, nulla, optio ipsa. ';
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  z-index: -1;
  opacity: 0.2; 
      min-height:50%; 
    min-width:50%;*/   
 /*   }  
#background{
    position:absolute;
    z-index:0;
    background:white;
    display:block;
    min-height:50%; 
    min-width:50%;
    color:yellow;
}

#bg-text
{
    color:lightgrey;
    font-size:120px;
    transform:rotate(225deg);
    -webkit-transform:rotate(225deg);
}*/

</style>
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-indigo-200 leading-tight no-print" {{-- style="border-bottom-left-radius: 50% 20%; border-bottom-right-radius: 50% 20%;" --}}>
            {{ Auth::user()->second_name }} 
            {{ Auth::user()->first_name }}
        </h2>
    </x-slot>    

    <div class="py-12">
        <div class="max-w-7xl {{-- mx-auto --}} sm:px-6 lg:px-8">
            <div class="p-6 sm:px-20 bg-white border-b border-gray-200 shadow-lg no-print">
                <div>
                    <x-jet-application-logo class="block h-12 w-auto" />
                </div>
        
                <div class="mt-8 space-y-4">
                    <h2 class="font-semibold text-4xl text-gray-300 tracking-wide">Hie {{ Auth::user()->first_name }} !</h2>
                    
                    <p class="font-thin text-lg">
                      @can('view',$exam_results[0])
                        You may want to view your 
                     @endcan 
                    @cannot('view',$exam_results[0])
                        To view your Harare Polytechnic's Hexco Examination Results ... 
                    @endcannot                                       
                    </p> 
                </div>

                <div class="mt-4 text-gray-500">
                      @can('view',$exam_results[0])
                        Fees Clearance Status ...
                     @endcan 
                     @cannot('view',$exam_results[0])                  
                    You must be fully paid up to Harare Polytechnic (with $0 balance or <span class="text-red-700">$-</span>) in your college account and be cleared by the accounts department.
                    @endcannot
                </div>
                <div class="my-2 py-12">
                  <a href="/results/clearance/{{Auth::user()->slug}}">
                    <button  class="float-right p-2 rounded-lg bg-indigo-500 text-white hover:text-indigo-500 hover:bg-white hover:border-4 hover:border-indigo-500" >
                      @can('view',$exam_results[0])
                        Fees Clearance Status 
                     @endcan                       
                      @cannot('view',$exam_results[0]) 
                        Send Proof of Payment
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="inline h-6 w-6">
                          <path fill-rule="evenodd" d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM6.293 6.707a1 1 0 010-1.414l3-3a1 1 0 011.414 0l3 3a1 1 0 01-1.414 1.414L11 5.414V13a1 1 0 11-2 0V5.414L7.707 6.707a1 1 0 01-1.414 0z" clip-rule="evenodd"/>
                        </svg>
                      @endcannot
                    </button>  
                  </a>                  

                </div>

            </div>  

            <div class="bg-gray-200 bg-opacity-25">
                <div class="p-6 relative">
                    <div class="flex items-center">
                        <x-icon name="academic-cap" class="h-14 w-14 text-gray-200"/>
                    </div>

                    <section name="exam_results" class="ml-12 p-2 shadow">
                        <div class="mt-2 text-sm text-gray-500">


                        @if($exam_results->count()>0)
                          @can('view',$exam_results[0])
                    {{-- watermark --}}
  {{-- <div id="background">
  <p id="bg-text">Background</p>
  </div> --}}
                       <article class="exam_results">
                            <div class="text-center border-b">
                                <h2 class="border-b text-lg font-thin">MINISTRY OF HIGHER AND TERTIARY EDUCATION, SCIENCE AND TECHNOLOGY DEVELOPMENT</h2>
                                <p class="text-xl font-extrabold">HIGHER EDUCATION EXAMINATIONS COUNCIL</p>
                                <p class="text-xl font-extrabold">(HEXCO)</p>
                                <p class="text-xl font-extrabold">INDIVIDUAL STATEMENT OF RESULTS</p>
                                <p class="no-print"> 
                                  <button class="cursor-pointer p-2" onclick="window.print()">
                                    <x-icon="document-download" class="h-8 w-8 text-red-900" stroke-width="2"/>
                                      download
                                  </button>
                                </p>    
                            </div>
                            <div class="my-4 py-2 w-1/2">
                                <p class="flex justify-between sm:space-x-6"><span class="font-bold">CANDIDATE NUMBER</span><span>:{{$exam_results[0]->candidate_number}}</span></p>
                                <p class="flex justify-between sm:space-x-6"><span class="font-bold">COMMENT</span><span>:{{$exam_results[0]->comment}}</span></p>
                                <p class="flex justify-between"><span class="font-bold">SURNAME</span><span>:{{$exam_results[0]->surname}}</span></p>
                                <p class="flex justify-between"><span class="font-bold">FIRST NAMES</span><span>:{{$exam_results[0]->names}}</span></p>
                                <p class="flex justify-between"><span class="font-bold">INSTITUTION NAME</span><span>:Harare Polytechnic</span></p>
                                <p class="flex justify-between"><span class="font-bold">COURSE LEVEL</span><span>{{$exam_results[0]->course_code}}</span></p>
                                <p class="flex justify-between"><span class="font-bold">COURSE TITLE</span><span class="text-red-700">:{{$exam_results[0]->discipline}}</span></p>
                            </div>
                        
              <table class="w-full">
                <thead>

                  <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b">

                    <th class="px-4 py-3">PAPER No.</th>
                    <th class="px-4 py-3">APPROVED SUBJECT TITLES </th>
                    <th class="px-4 py-3">GRADE</th>
                    <th class="px-4 py-3">Date</th>
                  </tr>
                </thead>

                <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
              
               @foreach($exam_results as $exam_result)   
                  <tr class="bg-gray-100  text-gray-700">
        <div class="text-gray-50 container__watermark text-4xl space-y-2 opacity-25" style=" transform: rotate(-45deg); position:absolute; width: 100%; margin: 0 auto; opacity: 0.25;">
            <p>Not for Official Use Not for Official Use</p>
        </div>                     
                    <td class="px-4 py-3">
                      <div class="flex items-center text-sm">
                        <div>
                          <p class="font-semibold">{{$exam_result->subject_code}}</p>
                        </div>
                      </div>
                    </td>
                    <td class="px-4 py-3 text-sm">{{$exam_result->subject}}</td>
                    <td class="px-4 py-3 text-sm">{{$exam_result->grade}}</td>
                    <td class="px-4 py-3 text-sm">{{$exam_result->session}} </td>
                 </tr>
                @endforeach              
                </tbody>
              </table>

              @endcan

                        @else
                        <p>There is no record of results. You may need to contact exams</p>

                       </article>                     
                        @endif
                        </div>
                </section>
                </div>                     
        </div>
    </div>        
</x-app-layout>  
</div>

resources/views/results/show.blade.php
<div>
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-indigo-200 leading-tight">
            {{ __('My fees clearance status') }} 
        </h2>
    </x-slot> 

    <div class="py-12">
        <div class="max-w-7xl {{-- mx-auto --}} sm:px-6 lg:px-8 bg-indigo-200 shadow-inner">
            <div class="mb-6 p-6 sm:px-20 bg-white border-b border-gray-200 shadow-lg rounded-lg">
                <div>
                    <x-jet-application-logo class="block h-12 w-auto" />
                </div>

                <div class="mt-8 text-2xl text-gray-300">
                    Welcome to Harare Polytechnic's Hexco Examination Results!
                </div>

                <div class="mt-6 text-gray-500">
                   @can('sendProof', $fees_clearances[0]) {{-- not able to view results unless admin --}}
                    You are not currently cleared by the accounts department to view your current Harare Polytechnic Hexco Results. You may need to upload proof of fees payment.
                   @endcan 
                   @cannot('sendProof', $fees_clearances[0])
                    You have been cleared by the accounts department and you are able to view your current Harare Polytechnic Hexco Results.
                   @endcannot

                </div>
            </div>

            <div class="my-24 p-6 sm:px-20 bg-white rounded-lg">
              <table class="w-full">
                <thead>
                  <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b">
                    <th class="px-4 py-3">Student</th>
                    <th class="px-4 py-3">Discipline</th>
                    <th class="px-4 py-3">Status</th>
                    <th class="px-4 py-3">Processed by</th>
                    <th class="px-4 py-3">Date</th>
                    <th class="px-4 py-3">Session</th>
                  </tr>
                </thead>
                <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
               @foreach($fees_clearances as $fee_clearance)
                  <tr class="bg-gray-50  text-gray-700">
                    <td class="px-4 py-3">
                      <div class="flex items-center text-sm">
                        <div class="relative hidden w-8 h-8 mr-3 rounded-full md:block">
                          <img class="object-cover w-full h-full rounded-full" src="{{$fee_clearance->user->profile_photo_url}}" alt="{{$fee_clearance->user->second_name}}"  />
                          <div class="absolute inset-0 rounded-full shadow-inner" aria-hidden="true"></div>
                        </div>
                        <div>
                          <p class="font-semibold">{{$fee_clearance->user->second_name}} {{$fee_clearance->user->first_name}}</p>
                          <p class="text-xs text-gray-600 dark:text-gray-400">{{$fee_clearance->user->national_id}}</p>
                        </div>
                      </div>
                    </td>
                    <td class="px-4 py-3 text-sm">{{$fee_clearance->user->results[0]->discipline}}</td>
                    <td class="px-4 py-3 text-xs">

                     @if($offline_cleared) 
                    <span class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full"> 
                        Approved
                        <x-icon name="check-circle" class="inline w-4 h-4"/>
                    </span>                     
                     @elseif($fee_clearance->cleared_at == null && $fee_clearance->is_cleared == false)
                        <span class="px-2 py-1 font-semibold leading-tight text-yellow-700 bg-yellow-100 rounded-full"> 
                            Pending
                        </span>                         
                     @elseif(!$fee_clearance->cleared_at == null && $fee_clearance->is_cleared == false)
                        <span class="px-2 py-1 font-semibold leading-tight text-red-700 bg-red-100 rounded-full"> 
                            Declined
                        </span>
                     @elseif(!$fee_clearance->cleared_at == null && $fee_clearance->is_cleared)
                        <span class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full"> 
                            Approved
                        </span>
                     @endif
                      <p class="text-xs text-gray-600 dark:text-gray-400">
                        {{!is_null($fee_clearance->cleared_at)? $fee_clearance->cleared_at->diffForHumans():''}}
                      </p>
                    </td>
                    <td class="px-4 py-3 text-sm">
                      <p class="font-semibold">
                        {{-- {{!is_null($fee_clearance->clearer_id)? 'Accounts Department':''}} --}}
                    @can('showName',$fee_clearance)
                        {{$fee_clearance->approver->second_name ?? false}}
                        {{$fee_clearance->approver->first_name ?? false}}                        
                    @endcan
                        Accounts Department                        
                      </p>
                      <p class="text-xs text-gray-600 dark:text-gray-400">
                        {{!is_null($fee_clearance->clearer_id)? Carbon\Carbon::parse($fee_clearance->cleared_at)->format('D d M Y h:i:s'): ''}}
                      </p>
                    </td>
                    <td class="px-4 py-3 text-sm">{{$fee_clearance->updated_at}}</td>
                    <td>{{$fee_clearance->intake->label}}</td>
                  </tr>
                @endforeach              
                </tbody>
              </table>
            </div>
            <div class="{{-- mb-6 p-6 sm:px-20 bg-white border-b border-gray-200 shadow-lg --}}">
                <div class="my -2">
                @livewire('comment.get-comments',['fileableId'=>$fee_clearance->id,'fileableType' =>'App\Models\Fee','isFromStudent'=>true])  
                </div>
            </div>
        @can('sendProof', $fees_clearances[0]) {{-- not able to view results unless admin --}}
            <div class="mb-6 p-6 sm:px-20 bg-white border-b border-gray-200 shadow-lg">           
                @livewire('comment.comment-upload',['fileableId'=>$fee_clearance->id,'fileableType' =>'App\Models\Fee','isFromStudent'=>true, 'possibleNewProofOfPayment'=>true,])            
            </div>
        @endcan
        </div>

        
    </div>
</x-app-layout>
</div>